### ISSUE TITLE
Don't have tool bar

### ISSUE THREAD

**Issue by zhangluwei1997** [Cardiac-MR-Group-Lund/segment-open#6]
### Steps to reproduce
1. Start Matlab.
2. Run segment_main.m.
3. Select MRI.
### Details
Version/commit: 
Matlab :R2017b
OS : Mac OS 10.14.4
I have installed  'MCR_R2014a_maci64_installer'.

Could you tell me how to solve it ? 
Thank you very much!
![image](https://user-images.githubusercontent.com/33014193/58247723-e7d68580-7d8c-11e9-9a5f-dcc9f355f179.png)

**Comment by johannestoger** [comment]
Hi, thanks for the bug report.

This is a known error due to the fact that you are using a Matlab version later than R2014a. There was a new GUI engine introduced in R2014b that is not compatible with Segment.

We are currently working on a port of Segment to R2019a, which should be available within a month or two I think.

The source code version of Segment does not use the MCR, so installing 2014a MCR does not help unfortunately, and you need to install Matlab R2014a. You might be able to download this version from Mathworks using your university account, if you have one.

**Comment by johannestoger** [comment]
Hi, we have now pushed the R2019a port.
